image: maven:latest

cache:
  paths:
    - .m2/
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

compile:
  stage: build

  artifacts:
    paths:
        - nerus-lib/target/*.jar
        - nerus-mdl/target/*.jar
        - nerus-app/target/*.jar
  script:
    - pwd
    - cd nerus-parent
    - mvn clean install verify