image: maven:latest

compile:
  stage: build
  artifacts:
    paths:
        - nerus-lib/target/*.jar
        - nerus-mdl/target/*.jar
        - nerus-app/target/*.jar
  cache:
    paths:
      - /root/.m2/*
      - /root/.m2/repository/
  script:
    - cd nerus-parent
    - mvn clean install verify
    - ls -al /root/.m2
    - ls -al /root/.m2/repository