image: maven:latest

compile:
  stage: build
  cache:
   paths:
    - ${USER_HOME}/.m2
  artifacts:
    paths:
        - nerus-lib/target/*.jar
        - nerus-mdl/target/*.jar
        - nerus-app/target/*.jar
  script:
    - cd nerus-parent
    - mvn clean install verify