image: maven:latest

cache:
  paths:
    - /root/.m2
  key: "$CI_BUILD_REF_NAME"

compile:
  stage: build
  artifacts:
    paths:
        - nerus-lib/target/*.jar
        - nerus-mdl/target/*.jar
        - nerus-app/target/*.jar
  script:
    - whoami
    - echo $HOME
    - pwd
    - cd nerus-parent
    - mvn clean install verify
    - ls -al /root/.m2