image: maven:latest

compile:
  stage: build
  cache:
   paths:
    - /cache
  artifacts:
    paths:
        - target/*.jar
  script:
    - cd nerus-parent
    - mvn clean install verify -Dmaven.repo.local=/cache