image: maven:latest

cache:
  paths:
    - /root/.m2/*
    - /root/.m2/repository/

compile:
  stage: build
  artifacts:
    paths:
        - nerus-lib/target/*.jar
        - nerus-mdl/target/*.jar
        - nerus-app/target/*.jar
  script:
    - ls -al /root/.m2
    - cd nerus-parent
    - mvn clean install verify