image: maven:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

compile:
  #Stage
  stage: build
  #Artifacts
  artifacts:
    paths:
        - nerus-lib/target/*.jar
        - nerus-mdl/target/*.jar
        - nerus-app/target/*.jar
  #Run Script
  script:
    - cd nerus-parent
    - mvn clean install verify