package de.b4sh.nerus.lib.generator;

import java.security.SecureRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * SecureRandomByteArrayGenerator implements IByteArrayGenerator interface and provides the functionality for a
 * random generated byte array with a higher security concern. Check the SecureRandom java implementation for futher
 * details on the generation of byte arrays.
 *
 * @author deB4SH
 * @see de.b4sh.nerus.lib.generator.IByteArrayGenerator
 * @since 0.0.1
 */
public class SecureRandomByteArrayGenerator implements IByteArrayGenerator {

    private static final Logger log = Logger.getLogger(SecureRandomByteArrayGenerator.class.getName());
    private final SecureRandom random;

    public SecureRandomByteArrayGenerator() {
        this.random = new SecureRandom();
    }

    @Override
    public byte[] generateArray(final int length) {
        if (length == 0) {
            SecureRandomByteArrayGenerator.log.log(Level.INFO, "A length of zero is not valid for the generateArray " +
                    "function.");
            return null;
        }
        final byte[] array = new byte[length];
        this.random.nextBytes(array);
        return array;
    }

    @Override
    public byte[] generateArray() {
        return this.generateArray(1024);
    }
}
